<a href="https://colab.research.google.com/github/dnjswlcks67/pdm12/blob/main/notebook/numpy_ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
 b[0][2]

3

In [8]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

In [9]:
a.shape

(3, 3)

In [10]:
a.ndim

2

In [11]:
a.dtype

dtype('int64')

In [12]:
a.itemsize

8

In [13]:
a.size

9

In [14]:
np.zeros( (3, 4) )	

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones( (3, 4), dtype=np.int32 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
x = np.ones(5, dtype=np.int64)

In [18]:
x

array([1, 1, 1, 1, 1])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [22]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])

In [26]:
y = np.array([[5, 6], [7, 8]])

In [27]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [28]:
np.vstack((x, y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.hstack((x, y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
a = np.arange(12)

In [31]:
a.shape

(12,)

In [32]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
array = np.arange(30).reshape(-1, 10)

In [35]:
array 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
arr1, arr2 = np.split(array, [3], axis=1)

In [37]:
arr1

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [38]:
arr2

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])


In [40]:
a.shape

(6,)

In [41]:
a1 = a[np.newaxis, :]

In [42]:
a1

array([[1, 2, 3, 4, 5, 6]])

In [43]:
a1.shape

(1, 6)

In [44]:
a2 = a[:, np.newaxis]

In [45]:
a2.shape

(6, 1)

In [46]:
ages = np.array([18, 19, 25, 30, 28])

In [47]:
ages[1:3] 

array([19, 25])

In [48]:
ages[:2] 

array([18, 19])

In [49]:
y = ages > 20

In [50]:
y

array([False, False,  True,  True,  True])

In [51]:
ages[ ages > 20 ]

array([25, 30, 28])

In [52]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [53]:
a[0, 2]

3

In [54]:
a[0, 0] = 12

In [55]:
a

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [56]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [57]:
a[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [58]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [59]:
arr2 = np.array([[1, 1], [1, 1], [1, 1]])

In [60]:
result = arr1 + arr2

In [61]:
result

array([[2, 3],
       [4, 5],
       [6, 7]])

In [62]:
miles = np.array([1, 2, 3])

In [63]:
result = miles * 1.6

In [64]:
result

array([1.6, 3.2, 4.8])

In [65]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

In [66]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [67]:
result = arr1 * arr2

In [68]:
result

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [69]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [70]:
arr2 = np.array([[2, 2], [2, 2], [2, 2]])

In [71]:
result = arr1 @ arr2

In [72]:
result

array([[12, 12],
       [30, 30],
       [48, 48]])

In [73]:
A = np.array([0, 1, 2, 3])


In [74]:
10 * np.sin(A)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [75]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [76]:
a.sum()

45

In [77]:
a.min()

1

In [78]:
a.max()

9

In [79]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    

In [80]:
scores.mean(axis=0)

array([92.  , 80.5 , 78.75])

In [81]:
np.random.seed(100)


In [82]:
np.random.rand(5)


array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [83]:
np.random.rand(5, 3)


array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [84]:
np.random.randn(5)

array([ 0.67272081, -0.10441114, -0.53128038,  1.02973269, -0.43813562])

In [85]:
np.random.randn(5, 4)

array([[-1.11831825,  1.61898166,  1.54160517, -0.25187914],
       [-0.84243574,  0.18451869,  0.9370822 ,  0.73100034],
       [ 1.36155613, -0.32623806,  0.05567601,  0.22239961],
       [-1.443217  , -0.75635231,  0.81645401,  0.75044476],
       [-0.45594693,  1.18962227, -1.69061683, -1.35639905]])

In [86]:
m, sigma = 10, 2

In [87]:
m + sigma*np.random.randn(5)

array([ 7.53513097,  8.91112168,  8.66365653, 10.01462913,  8.77412253])

In [88]:
mu, sigma = 0, 0.1 	# 평균과 표준 편차

In [89]:
np.random.normal(mu, sigma, 5)

array([ 0.12997481, -0.17330956, -0.09833101,  0.03575078, -0.16135785])

In [90]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [91]:
unique_values = np.unique(a)

In [92]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [93]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

[[1 3 5]
 [2 4 6]]


In [94]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [95]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

FileNotFoundError: ignored

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()

In [ ]:
X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()

In [ ]:
import matplotlib.pyplot as plt 
import numpy as np 
import math 
  
X = np.linspace(-10, 10, 100) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 100) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 